name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
        
      - name: 'Test 1'
        shell: bash
        run: |
          echo "GIT_BRANCH=${GITHUB_REF##*/}"
          echo $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: 'Load env'
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ${{ env.GIT_BRANCH }}
          
      - name: 'Test 2'
        shell: bash
        run: |
            echo ${{ env.TEST }}
            echo $TEST
            echo ${{ env.MEM }}
            
            cat $GITHUB_ENV
